name: gql_phoenix_link
description: A graphql link using phoenix sockets
version: 0.2.0
homepage: https://github.com/knaeckeKami/gql_phoenix_link

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  phoenix_socket: ^0.5.3
  gql_exec: ^0.4.0
  gql_link: ^0.4.2

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.1
